In [184]:
# Useful starting lines
%matplotlib inline
import numpy as np
'''ONLY FOR VISUALIZATION'''
import pandas as pd 
import matplotlib.pyplot as plt
'''ONLY FOR VISUALIZATION'''
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Load the training data into feature matrix, class labels, and event ids:

In [185]:
from proj1_helpers import *
#Modify DATA_PATH if needed
DATA_TRAIN_PATH = '/Users/wifinaynay/downloads/data_project1/train.csv'
y, tX_old, ids = load_csv_data(DATA_TRAIN_PATH)

In [186]:
'''DATASET INTRINSICS AND SHAPE (TARGETS AND IDS INCLUDED)'''
def DataSetInfo(y, tX_old, ids):
    print("Training examples: ", tX_old, " & shape: ")
    print("Targets: ", y)
    print("Ids: ",ids)
    print("Shapes of tX, y & Ids: ", tX_old.shape, y.shape, ids.shape)
DataSetInfo(y, tX_old, ids)

Training examples:  [[ 138.47    51.655   97.827 ...    1.24    -2.475  113.497]
 [ 160.937   68.768  103.235 ... -999.    -999.      46.226]
 [-999.     162.172  125.953 ... -999.    -999.      44.251]
 ...
 [ 105.457   60.526   75.839 ... -999.    -999.      41.992]
 [  94.951   19.362   68.812 ... -999.    -999.       0.   ]
 [-999.      72.756   70.831 ... -999.    -999.       0.   ]]  & shape: 
Targets:  [ 1. -1. -1. ...  1. -1. -1.]
Ids:  [100000 100001 100002 ... 349997 349998 349999]
Shapes of tX, y & Ids:  (250000, 30) (250000,) (250000,)


In [267]:
'''INITIALIZE WEIGHTS'''
def InitWeights(feat):
    ww = np.random.rand(feat)
    init_w = np.array(ww, dtype=np.float64)
    return init_w

'''HYPER PARAMETERS'''
def HyperParameters():
    max_iter = 800
    epochs = 10
    gamma = 1e-1
    lambda_ = 1e-2
    return max_iter, epochs, gamma, lambda_

'''TAKE LOG TRANSFORMATION OF FEATURES'''
def LogTransformData(tX, features):  
    data = tX[:, features]
    indices = np.where(data > -999)
    data[indices] = np.log(1 + data[indices])
    tX = ManipulateFeatures(tX, data, features)    
    return tX

'''DELETE GIVEN FEATURE VECTOR FROM FEATURE AND CONCETENATE WITH NEW DATA '''
def ManipulateFeatures(tX, data,features):
    tX = np.delete(tX, features, 1)
    return np.hstack((tX, data))

'''IMPUTE DATA WITH MEANS'''
def ImputeData(tX):
    tX = np.where(tX == -999, np.nan, tX)
    #Remove all columns with NAN
    tX = tX[:, ~np.all(np.isnan(tX), axis=0)]
    
    #Remove highly correlated features
    tX = tX[:, ~np.all(tX[1:] == tX[:-1], axis=0)]

    #Find Mean excluding NAN values
    tX_mean = np.nanmean(tX, axis=0)

    # NAN = MEAN
    tX[np.where(np.isnan(tX))] = np.take(tX_mean, np.where(np.isnan(tX))[1])
    print(tX.shape)
    return tX

'''STANDARDIZE'''
def Standardize(x):
    mean_x = np.mean(x, axis=0)
    x = x - mean_x
    std_x = np.std(x, axis=0)
    x[:, std_x > 0] = x[:, std_x > 0] / std_x[std_x > 0]
    return x, mean_x, std_x

'''PREPROCESS'''
def PreProcess(tX):
    print(tX.shape)
    '''FEATURES PICKED BY HAND'''
    log_feature_vec = np.array(([0, 2, 5, 9, 13, 16, 19, 21, 23, 26, 29]))
    '''LUCKY FEATURE OF THE WEEK: 30 :)'''
    lucky_feature = np.array(([30]))
    tX = LogTransformData(tX, log_feature_vec)
    tX = ImputeData(tX)
    tX = Standardize(tX)[0]
    return tX

'''DATASET SEPERATED IN TERMS OF CATEGORIES IN COLUMN 22'''
def Categorize_Train(y, tX, ids):
    '''CATEGORIES '''
    ind = [[] for j in range(3)]
    xx = [[] for j in range(3)]
    yy = [[] for j in range(3)]
    iids = [[] for j in range(3)]
    
    for i in range(3): 
        ind[i] = np.nonzero(tX[:, 22] == i)[0]
        xx[i] = tX[ind[i]]
        yy[i] = y[ind[i]]
        iids[i] = ids[ind[i]]
        
    return np.array((yy)), np.array((xx)), np.array((iids)), np.array((ind))

def Categorize_Test(tX, ids):
    '''CATEGORIES '''
    ind = [[] for j in range(3)]
    xx = [[] for j in range(3)]
    iids = [[] for j in range(3)]
    
    for i in range(3): 
        ind[i] = np.nonzero(tX[:, 22] == i)[0]
        xx[i] = tX[ind[i]]
        iids[i] = ids[ind[i]]
        
    return xx, iids, ind

'''PREDICTIONS INTO COMPARABLE FORM'''
def Decategorize(y_cat, ind):
    size = y_cat[0].shape[0] + y_cat[1].shape[0] + y_cat[2].shape[0]
    y = np.zeros((size,), dtype=np.float)
    for i in range(len(y_cat)):
        y[ind[i]] = y_cat[i]
    return y

'''CHECK VALIDATION SCORE'''
def WeightedAverage(pred, target):
    total_count = pred[0].shape[0] + pred[1].shape[0] + pred[2].shape[0]
    true_count = 0
    for i in range(3):
        true_count +=  np.sum(pred[i] == target[i])
    acc = true_count / total_count
    return acc
'''FEATURE CORRELATION MAP: ONLY FOR VISUALIZATION'''
'''CORRELATED FEATURES: CORR > THRESHOLD : USE FOR SYNTHESIS'''
def CorrMap(tX):
    df = pd.DataFrame(tX)
    corr = df.corr()
    return corr.style.background_gradient(cmap='coolwarm')

'''FEATURE ENGINEERING'''
def FeatureSynthesis(tX_pp, tX_old):
    '''CORRELATED FEATURES WILL BE USED FOR NEW FEATURE ADDITION'''
    '''MIN PART'''
    #tX = np.hstack((tX_pp, np.minimum((tX_old[:,15:16] - tX_old[:,18:19]),np.minimum((tX_old[:,15:16] - tX_old[:,20:21]),(tX_old[:,18:19] - tX_old[:,20:21])))))                                           
    tX = np.hstack((tX_pp, np.minimum((tX_old[:,15:16] - tX_old[:,20:21]),(tX_old[:,18:19] - tX_old[:,20:21]))))
    tX = np.hstack((tX, np.minimum((tX_old[:,15:16] - tX_old[:,18:19]),(tX_old[:,15:16] - tX_old[:,20:21]))))
    tX = np.hstack((tX, (tX_old[:,18:19] - tX_old[:,20:21])))
    '''LN PART'''
    #tX = np.hstack((tX, np.log(np.abs(min((tX_old[:,13:14]*tX_old[:,14:15])))+(tX_old[:,13:14]*tX_old[:,14:15]))))                                                                                         
    #tX = np.hstack((tX, np.log(np.abs(min((tX_old[:,16:17]*tX_old[:,17:18])))+(tX_old[:,16:17]*tX_old[:,16:17]))))                                                                                         
    #tX = np.hstack((tX, np.log(np.abs(min((tX_old[:,23:24]*tX_old[:,24:25])))+(tX_old[:,23:24]*tX_old[:,24:25]))))                                                                                         
    return tX

'''RANDOM DATA SPLIT'''
def RandomizedDataSplit(tX, y, ids, inds, split_size = 0.1, my_seed=1):
    '''SET SEED FOR REMOVING RANDOMNESS'''
    #np.random.seed(my_seed)
    '''RANDOM INDEXES'''
    size = y.shape[0]
    ind = np.random.permutation(size)
    split = int(np.floor(split_size * size))
    
    ind_train = ind[split:]
    ind_valid = ind[:split]
    
    
    '''SPLIT DATA ACCORDING TO RANDOM INDICES'''
    tX_train = tX[ind_train]
    tX_valid = tX[ind_valid]
    y_train = y[ind_train]
    y_valid = y[ind_valid]
    ids_train = ids[ind_train]
    ids_valid = ids[ind_valid]
    inds_train = inds[ind_train]
    inds_valid = inds[ind_valid]
    
    print("Shapes of tX, y, Ids & Indices for Training: ", tX_train.shape, y_train.shape, ids_train.shape, inds_train.shape)
    print("Shapes of tX, y, Ids & Indices for Validation: ", tX_valid.shape, y_valid.shape, ids_valid.shape, inds_valid.shape)
    return (tX_train, y_train, ids_train, inds_train),(tX_valid, y_valid, ids_valid, inds_valid)

'''BACKWARD SELECTION METHOD FOR BEST FEATURE SELECTION: GREEDY APPROACH'''
def BackwardSelection(y, tX, tX_valid, y_valid, model = "RR"):
    
    selected_features = []
    cur_best_acc = 0
    improved = True     
    while improved:
        improved = False
        worst_ft = -1 
        for i in range(tX.shape[1]):
            if i not in selected_features:
                
                diff = set(list(range(tX.shape[1]))) - set(selected_features + [i])            
                #calculate accuracy
                #print(tX[:,list(diff)].shape,y.shape)
                
                cur_acc = CrossValidation(y, tX[:,list(diff)],10)
                #print(cur_acc)
                #accuracy is improved
                if cur_best_acc <= cur_acc:
                    #print("best so far: ",cur_best_acc)
                    improved = True
                    cur_best_acc = cur_acc
                    worst_ft = i                    
        if improved:
            selected_features.append(worst_ft)  
        #print("burada",improved)
            
    return list(set(list(range(tX.shape[1]))) - set(selected_features )), cur_best_acc

'''FORWARD OF BACKWARD SELECTION'''
def Selection(y, tX, tX_valid, y_valid, typ = "BS", model = "RR"):
    if typ == "BS":
        selected_features, cur_best_acc = BackwardSelection(y, tX, tX_valid, y_valid,model)
        return selected_features, cur_best_acc
    elif typ == "FS":
        selected_features, cur_best_acc = ForwardSelection(y, tX, tX_valid, y_valid,model) 
        return selected_features, cur_best_acc
    
'''FORWARD SELECTION METHOD FOR BEST FEATURE SELECTION: GREEDY APPROACH'''
def ForwardSelection(y, tX, tX_valid, y_valid, model = "RR"):    
    selected_features = []
    cur_best_acc = 0  
    improved = True
    while improved:
        
        improved = False
        best_ft = -1 
        for i in range(tX.shape[1]):
            if i not in selected_features: 
                
                #calculate accuracy
                
                cur_acc = CrossValidation(y, tX[:,selected_features+[i]],5)
                #print(cur_acc)
                #accuracy is improved
                if cur_best_acc <= cur_acc:
                    improved = True                   
                    cur_best_acc = cur_acc
                    best_ft = i                 
                    
        if improved:
            selected_features.append(best_ft)
            #print(selected_features)
         
    return selected_features, cur_best_acc

'''CROSS VALIDATION HELPER FUNCTION'''
def SelectIndices(y, k_fold, seed):
    row_count = y.shape[0]
    window_size = int((row_count / k_fold))
    remainder = row_count % k_fold
    np.random.seed(seed)
    rand_indices = np.random.permutation(row_count)
    indices = [[] for i in range(k_fold)]
    
    for k in range(k_fold):
        
            indices[k] = [rand_indices[k*window_size:(k+1)*window_size]]
            
    return np.array(indices)

'''ADD NEW FUTURES'''
def AddFeatures(tX):
    prime_numbers = [2,3]
    #ADD COS / SIN , SQRT 
    #CHECK FEATURE SYNTHESIS
    pm = 0
    loop_count = tX.shape[1]
    for pm in range(len(prime_numbers)):
        for i in range(loop_count):
            tX = np.hstack((tX, np.power(tX[:,i], prime_numbers[pm]).reshape(-1,1)))
    for i in range(loop_count):
            tX = np.hstack((tX, np.cos(tX[:,i]).reshape(-1,1)))
    for i in range(loop_count):
            tX = np.hstack((tX, np.sin(tX[:,i]).reshape(-1,1)))
    
    return tX

'''REMOVE USELESS FEATURES'''
def RemoveFeatures(tX, ratio = 0.5):
    
    tX = np.hstack((tX[:,22].reshape(-1,1),np.delete(tX,22,1)))
    selected_indices = []
    
    for i in range(tX.shape[1]):
        res = np.count_nonzero(tX[:,i] == -999)
        
        if (res / tX.shape[0]) > ratio:
            print(i)
            selected_indices.append(i)
    diff = list(set(list(range(tX.shape[1])))- set(selected_indices))
    return tX[:,diff]

'''CROSS VALIDATION'''
def CrossValidation(y, tX, k):
    seed = np.random.randint(10)
    indices = SelectIndices(y,k,seed)
    average_acc = 0
    for i in range (k):        

        xk_train = tX[~indices[i]]
        xk_valid = tX[indices[i]]
        yk_train = y[~indices[i]]
        yk_valid = y[indices[i]]
        #print(yk_train.shape,xk_train.shape)
        #print(xk_valid.shape)
        max_iter, epochs, gamma, lambda_ = HyperParameters()
        init_w_gd = np.array((InitWeights(xk_train[0].shape[1])))
        
        (w3,loss3) = ridge_regression(yk_train[0], xk_train[0], 0.05)
        ls_tr_pred = predict_labels(w3, xk_valid[0])
        #print("heree",(ls_tr_pred == yk_valid[0]).mean())
        average_acc += (ls_tr_pred == yk_valid[0]).mean()/k

    return average_acc
    
'''BUILD FULL DATA MODEL WITH CATEGORIZATION'''
def BuildDataModel_Train(y, tX_old, ids):
    y_cat, tX_cat, id_cat, ind_cat = Categorize_Train(y, tX_old, ids)
    
    for cat_ in range(tX_cat.shape[0]):
        
        tX_cat[cat_] = PreProcess(tX_cat[cat_])
        #tX_cat[cat_] = RemoveFeatures(tX_cat[cat_])
        tX_cat[cat_] = AddFeatures(tX_cat[cat_])
        
        
        
    

    '''TRAIN SET'''
    tX_tr_cat = [[] for j in range(3)]
    y_tr_cat = [[] for j in range(3)]
    id_tr_cat = [[] for j in range(3)]
    ind_tr_cat = [[] for j in range(3)]

    '''VALID SET'''
    tX_val_cat = [[] for j in range(3)]
    y_val_cat = [[] for j in range(3)]
    id_val_cat = [[] for j in range(3)]
    ind_val_cat = [[] for j in range(3)]

    for i in range(len(tX_cat)):
        (tX_tr_cat[i], y_tr_cat[i],id_tr_cat[i],ind_tr_cat[i]), (tX_val_cat[i], y_val_cat[i],id_val_cat[i], ind_val_cat[i]) = RandomizedDataSplit(tX_cat[i], y_cat[i], id_cat[i], ind_cat[i])

    '''CONVERT TRAIN AND DATASET INTO NUMPY ARRAYS'''
    tX_tr_cat = np.array((tX_tr_cat))
    y_tr_cat = np.array((y_tr_cat))
    id_tr_cat = np.array((id_tr_cat))
    ind_tr_cat = np.array((ind_tr_cat))

    tX_val_cat = np.array((tX_val_cat))
    y_val_cat = np.array((y_val_cat))
    id_val_cat = np.array((id_val_cat))
    ind_val_cat = np.array((ind_val_cat))

    return (y_tr_cat, tX_tr_cat, id_tr_cat, ind_tr_cat), (y_val_cat, tX_val_cat, id_val_cat, ind_val_cat)
   

'''BUILD FULL DATA MODEL WITH CATEGORIZATION'''
def BuildDataModel_Test(tX_old, ids):
    tX_cat, id_cat, ind_cat = Categorize_Test(tX_old, ids)
    
    for i in range(len(tX_cat)):
        tX_cat[i] = PreProcess(tX_cat[i])
       
    '''CONVERT TRAIN AND DATASET INTO NUMPY ARRAYS'''
    tX_cat = np.array((tX_cat))
    id_cat = np.array((id_cat))
    ind_cat = np.array((ind_cat))
    
    return tX_cat, id_cat, ind_cat

In [271]:
(y_cat, tX_cat, ids_cat, ind_cat), (y_val_cat, tX_val_cat, ids_val_cat, ind_val_cat) = BuildDataModel_Train(y,tX_old,ids)
y_cat = np.array((y_cat))
tX_cat = np.array((tX_cat))
ids_cat = np.array((ids_cat))
ind_cat = np.array((ind_cat))
print("Categorized y shape:", y_cat.shape)
print("Categorized tX shape:", tX_cat.shape)
print("Categorized ids shape:", ids_cat.shape)
print("Categorized ids shape:", ind_cat.shape)

(99913, 30)
(99913, 18)
(77544, 30)
(77544, 22)
(50379, 30)
(50379, 29)
Shapes of tX, y, Ids & Indices for Training:  (89922, 90) (89922,) (89922,) (89922,)
Shapes of tX, y, Ids & Indices for Validation:  (9991, 90) (9991,) (9991,) (9991,)
Shapes of tX, y, Ids & Indices for Training:  (69790, 110) (69790,) (69790,) (69790,)
Shapes of tX, y, Ids & Indices for Validation:  (7754, 110) (7754,) (7754,) (7754,)
Shapes of tX, y, Ids & Indices for Training:  (45342, 145) (45342,) (45342,) (45342,)
Shapes of tX, y, Ids & Indices for Validation:  (5037, 145) (5037,) (5037,) (5037,)
Categorized y shape: (3,)
Categorized tX shape: (3,)
Categorized ids shape: (3,)
Categorized ids shape: (3,)


## Do your thing crazy machine learning thing here :) ...

In [189]:
'''GRAD AND LOSS FUNCTIONS'''
def compute_loss(y, tx, w, typ):
    '''typ = <LOSS_TYPE(WITH CAPITAL LETTERS)>'''
    loss = 0
    N = y.shape[0]
    if typ == "MSE":
        loss = (1/(2*N))*np.sum(np.square(y - (tx@w)))        
    elif typ == "MAE":
        loss = (1/(2*N))*np.sum(np.abs(y - (tx@w)))
    return loss

def compute_gradient(y, tx, w):
    '''GRADIENT COMPUTATION'''
    N = y.shape[0]
    e = y - tx@w
    grad = (-1/N) * (tx.T@e)
    return grad

def compute_stoch_gradient(y, tx, w):
    '''STOCHASTIC GRADIENT DESCENT GRADIENT COMPUTATION''' 
    N = y.shape[0]
    e = y - tx@w
    grad = (-1/N)*(tx.T@e)
    return grad

def compute_ls_loss(y, tx, w):
    '''LEAST SQUARES WITH NORMAL EQUATIONS LOSS COMPUTATION'''
    loss = 0
    N = y.shape[0]
    loss = (1/(2*N))*(tx.T@(y - tx@w))
    
def compute_rdg_loss(y, tx, w, lambda_):
    '''RIDGE REGRESSION LOSS COMPUTATION'''
    loss = 0
    N = y.shape[0]
    loss = (1/(2*N))*np.sum(np.square(y - (tx@w))) + (lambda_*np.sum(w.T@w))
    return loss

def sigmoid(tx, w):
    '''SIGMOID CALCULATION'''
    z = 1 / (1 + np.exp(-1*(tx@w)))
    return z

def compute_log_loss(y, tx, w):
    '''LOGISTIC LOSS'''
    loss = 0;
    sigm = sigmoid(tx,w)
    N = y.shape[0]
    loss = (-1/N)*np.sum(y.T@np.log(sigm) + ((1-y).T@np.log(1 - sigm)))
    
    return loss
def compute_log_gradient(y, tx, w):
    '''GRADIENT COMPUTATION FOR LR'''
    N = y.shape[0]
    z = sigmoid(tx,w)
    grad = (1/N) * (tx.T@(z - y))
    return grad

def compute_reg_log_loss(y, tx, w, lambda_):
    '''LOGISTIC LOSS WITH REGULARIZATION'''
    loss = 0;
    sigm = sigmoid(tx,w)
    N = y.shape[0]
    loss = (-1/N)*(np.sum(y.T@np.log(sigm) + ((1-y).T@np.log(1 - sigm))) + ((lambda_/2)*np.sum(w.T@w)))
    
    return loss
def compute_reg_log_gradient(y, tx, w, lambda_):
    '''GRADIENT COMPUTATION FOR LR WITH REGULARIZATION'''
    N = y.shape[0]
    z = sigmoid(tx,w)
    grad = (1/N) * ((tx.T@(z - y)) + (lambda_*w))
    return grad

In [190]:
def least_squares_GD(y, tx, initial_w, max_iters, gamma):
    '''BATCH GRADIENT DESCENT'''
    w = initial_w
    for n_iter in range(max_iters):
        loss = compute_loss(y, tx, w, "MSE")
        grad = compute_gradient(y, tx, w)
        w = w - (gamma * grad)
        #print("Gradient Descent({bi}/{ti}): loss={l}".format(bi=n_iter, ti=max_iters - 1, l=loss))

    return (w, loss)

In [191]:
def least_squares_SGD(y, tx, initial_w, max_iters, gamma):
    '''STOCHASTIC GRADIENT DESCENT'''
    w = initial_w 
    for n_iter in range(max_iters):
        for minibatch_y, minibatch_tx in batch_iter(y, tx, 1):
            loss = compute_loss(minibatch_y, minibatch_tx, w, "MSE")
            grad = compute_gradient(minibatch_y, minibatch_tx, w)
            w = w - gamma * grad
            #print("Stochastic Gradient Descent({bi}/{ti}): loss={l}".format(bi=n_iter, ti=max_iters - 1, l=loss))
    return (w, loss)

In [192]:
def least_squares(y, tx):
    '''COMPUTE W_STAR: WEIGHT FOR NORMAL EQUATIONS BY LINEAR EQUATION SOLVER'''
    w_star = np.linalg.solve(tx.T@tx, tx.T@y)
    loss = compute_ls_loss(y, tx, w_star)
    return (w_star,loss)

In [193]:
def ridge_regression(y, tx, lambda_):
    '''RIDGE REGRESSION WITH LAMBDA PARAMETER AS REGULARIZATION PARAMETER'''
    N = y.shape[0]
    a = tx.shape[0]
    m = (tx.T@tx)+(lambda_/(2*N))*np.identity(tx.shape[1])
    i = np.eye(m.shape[0],m.shape[0])
    w_ridge = np.linalg.lstsq(m,i)[0]@tx.T@y
    loss = compute_rdg_loss(y, tx, w_ridge, lambda_)
    return (w_ridge, loss)
    

In [194]:
def logistic_regression(y, tx, initial_w, max_iters, gamma):
    '''FOR GRADIENT DESCENT'''
    w = initial_w
    for n_iter in range(max_iters):
        loss = compute_log_loss(y, tx, w)
        grad = compute_log_gradient(y, tx, w)
        w = w - (gamma * grad)
        #print("Logistic Regression Gradient Descent({bi}/{ti}): loss={l}".format(bi=n_iter, ti=max_iters - 1, l=loss))

    return (w, loss)
    '''FOR STOCHASTIC GRADIENT DESCENT'''
    '''
    w = initial_w 
    for n_iter in range(max_iters):
        for minibatch_y, minibatch_tx in batch_iter(y, tx, 1):
            loss = compute_log_loss(minibatch_y, minibatch_tx, w)
            grad = compute_log_gradient(minibatch_y, minibatch_tx, w)
            w = w - gamma * grad
            #print("Stochastic Gradient Descent({bi}/{ti}): loss={l}".format(bi=n_iter, ti=max_iters - 1, l=loss))
    return (w, loss)
    '''

In [195]:
def reg_logistic_regression(y, tx, lambda_, initial_w, max_iters, gamma):
    '''FOR GRADIENT DESCENT WITH REGULARIZATION'''
    '''FOR GRADIENT DESCENT'''
    w = initial_w
    for n_iter in range(max_iters):
        loss = compute_reg_log_loss(y, tx, w, lambda_)
        grad = compute_reg_log_gradient(y, tx, w, lambda_)
        w = w - (gamma * grad)
        #print("Logistic Regression Gradient Descent({bi}/{ti}): loss={l}".format(bi=n_iter, ti=max_iters - 1, l=loss))

    return (w, loss)
    '''FOR STOCHASTIC GRADIENT DESCENT'''
    '''
    w = initial_w 
    for n_iter in range(max_iters):
        for minibatch_y, minibatch_tx in batch_iter(y, tx, 1):
            loss = compute_reg_log_loss(minibatch_y, minibatch_tx, w, lambda_)
            grad = compute__reg_log_gradient(minibatch_y, minibatch_tx, w, lambda_)
            w = w - gamma * grad
            #print("Stochastic Gradient Descent({bi}/{ti}): loss={l}".format(bi=n_iter, ti=max_iters - 1, l=loss))
    return (w, loss)
    '''

## Generate predictions and save ouput in csv format for submission:

In [ ]:
DATA_TEST_PATH = '/Users/wifinaynay/downloads/data_project1/test.csv' # TODO: download train data and supply path here 
_, tX_test_old, ids_test = load_csv_data(DATA_TEST_PATH)

In [ ]:
(y_cat, tX_cat, ids_cat, ind_cat), (y_val_cat, tX_val_cat, ids_val_cat, ind_val_cat) = BuildDataModel_Train(y,tX_old,ids)

In [272]:
'''PREDICTIONS FOR MODELS'''
'''BATCH GD'''
init_w_gd = np.array((InitWeights(tX_cat[0].shape[1]),InitWeights(tX_cat[1].shape[1]),InitWeights(tX_cat[2].shape[1])))
gd_tr_pred = np.copy((y_val_cat))
w_gd = np.copy((init_w_gd))
max_iter, epochs, gamma, lambda_ = HyperParameters()
cat_lst = [0, 1, 2]
for cat in cat_lst:
    #res = ForwardSelection(y_cat[cat], tX_cat[cat], tX_val_cat[cat], y_val_cat[cat], "RR")
    #print("after forward:",res[0], res[1])
    #print("debugg", init_w_gd[cat][res[0]].shape)
    (w_gd[cat],loss1) = ridge_regression(y_cat[cat], tX_cat[cat],lambda_)
    #print(ww2.shape, tX_val_cat[cat][:,res[0]].shape )
    
    gd_tr_pred[cat] = predict_labels(w_gd[cat], tX_val_cat[cat])
    print(gd_tr_pred[cat])
#pred = Decategorize(gd_tr_pred, ind_val_cat)
acc = WeightedAverage(gd_tr_pred, y_val_cat)
print("Accuracy of Model:", acc)



/Users/wifinaynay/anaconda2/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:7: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  import sys


[-1. -1. -1. ... -1.  1. -1.]
[-1. -1. -1. ...  1. -1.  1.]
[ 1. -1.  1. ...  1. -1.  1.]
Accuracy of Model: 0.823588798173997


In [270]:
OUTPUT_PATH = '/Users/wifinaynay/downloads/data_project1/lr.csv' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(best_grad[0], tX_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)

NameError: name 'best_grad' is not defined